version: "3.6"

networks:
  default:

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - ${NGINX_HTTP_HOST_PORT}:80
      - ${NGINX_HTTPS_HOST_PORT}:443
    volumes:
      - ${BASE_PATH}:/var/www/html/:rw
      - ${BASE_PATH}/${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${BASE_PATH}/${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${BASE_PATH}/${NGINX_LIB_DIR}:/etc/nginx/lib/:ro
      - ${BASE_PATH}/${NGINX_CERT_DIR}:/etc/nginx/cert.d/:ro
      - ${BASE_PATH}/${NGINX_VHOST_DIR}:/etc/nginx/conf.d/:ro
      # - jenkins_home:/var/jenkins_home
    restart: always
    networks:
      - default
    environment:
      TZ: "${TZ}"

  gitlab:
    image: gitlab/gitlab-ee:${GITLAB_VERSION}
    restart: always
    environment:
      TZ: "${TZ}"
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://${GITLAB_HOSTNAME}"
      GITLAB_ROOT_PASSWORD: ${GITLAB_ROOT_PASSWORD}
    ports:
      - ${GITLAB_SSH_HOST_PORT}:22
      - ${GITLAB_HTTP_HOST_PORT}:9280
      - ${GITLAB_HTTPS_HOST_PORT}:9243
    volumes:
      - ${BASE_PATH}/${GITLAB_CONF_DIR}:/etc/gitlab
      - gitlab_backups:/opt/gitlab_backups
      - ${BASE_PATH}/${GITLAB_LOGS_DIR}:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - default

  gitlab-runner:
    image: gitlab/gitlab-runner:${GITLAB_RUNNER_VERSION}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_PATH}/${GITLAB_RUNNER_CONF_DIR}:/etc/gitlab-runner
    environment:
      TZ: "${TZ}"

  php70:
    build:
      context: ./build/php/
      args:
        PHP_VERSION: ${PHP70_VERSION}
        ALPINE_REPOSITORIES: ${ALPINE_REPOSITORIES}
        PHP_EXTENSIONS: ${PHP70_EXTENSIONS}
        MORE_EXTENSION_INSTALLER: php.sh
        TZ: "${TZ}"
    volumes:
      - ${BASE_PATH}:/var/www/html/:rw
      - ${PHP70_LOG_DIR}:/var/log/php
      - ${COMPOSER_CACHE_DIR}:/usr/local/composer
      - ${COMPOSER_CONFIG_FILE}:/usr/local/composer/config.json
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

volumes:
  gitlab_data:
  gitlab_backups:
